package net.fortresswars.core.game;

public enum FWBossBar {
    LOBBY,
    GAMERULE_VOTING,
    LOADING,
    CLASSIC_IN_GAME,
    CLASSIC_IN_BUILDING,
    KOTH_IN_PREGAME,
    KOTH_IN_GAME,
    AD_IN_BUILDING,
    AD_IN_PREROUND,
    AD_IN_GAME,
    AD_BETWEEN_ROUND,
    END_GAME,
    CLASSIC_SUDDEN_DEATH,
    KOTH_OVERTIME,
    GAME_PAUSED
}
