package net.fortresswars.core.kits;

import net.fortresswars.core.validators.DataValidationException;
import net.fortresswars.core.validators.DataValidator;
import net.fortresswars.core.validators.DataValidatorBuilder;

public enum KitData {

    // Tank Role
    TANK_ROLE_KNOCKBACK_PERCENTAGE(50, DataValidatorBuilder.create().range(0, 100).build()),

    // Armor
    CHESTPLATE_ARMOR(5, DataValidatorBuilder.create().range(0, 30).build()),
    CHESTPLATE_ARMOR_TOUGHNESS(0, DataValidatorBuilder.create().range(0, 20).build()),
    CHESTPLATE_PROTECTION_LEVEL(1, DataValidatorBuilder.create().range(0, 10).build()),
    CHESTPLATE_KNOCKBACK_RESISTANCE(0, DataValidatorBuilder.create().range(0, 1).build()),
    LEGGINGS_ARMOR(4, DataValidatorBuilder.create().range(0, 30).build()),
    LEGGINGS_ARMOR_TOUGHNESS(0, DataValidatorBuilder.create().range(0, 20).build()),
    LEGGINGS_PROTECTION_LEVEL(1, DataValidatorBuilder.create().range(0, 1).build()),
    LEGGINGS_KNOCKBACK_RESISTANCE(0, DataValidatorBuilder.create().range(0, 1).build()),
    BOOTS_ARMOR(1, DataValidatorBuilder.create().range(0, 30).build()),
    BOOTS_ARMOR_TOUGHNESS(0, DataValidatorBuilder.create().range(0, 20).build()),
    BOOTS_PROTECTION_LEVEL(1, DataValidatorBuilder.create().range(0, 1).build()),
    BOOTS_KNOCKBACK_RESISTANCE(0, DataValidatorBuilder.create().range(0, 1).build()),

    // Shield
    SHIELD_REGENERATION_DELAY(40, DataValidatorBuilder.create().integer().min(0).build()),
    SHIELD_REGENERATION_RATE(20, DataValidatorBuilder.create().integer().min(1).build()),
    SHIELD_REGENERATION_AMOUNT(20, DataValidatorBuilder.create().integer().min(1).build()),
    SHIELD_BREAK_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    SHIELD_DAMAGE_FACTOR(0.9, DataValidatorBuilder.create().range(0, 1).build()),
    SHIELD_BLOCKING_DELAY(0, DataValidatorBuilder.create().integer().min(0).build()),
    SHIELD_MAX_HEALTH(350, DataValidatorBuilder.create().integer().min(1).build()),

    // Potions
    POTION_OUT_OF_COMBAT_REGENERATION_RATE(100, DataValidatorBuilder.create().integer().min(0).build()),
    POTION_IN_COMBAT_REGENERATION_RATE(200, DataValidatorBuilder.create().integer().min(0).build()),

    // Healing Potions
    MAX_HEALING_POTIONS(7, DataValidatorBuilder.create().integer().min(0).build()),
    HEALING_POTION_CLICK_POTENCY(7.5, DataValidatorBuilder.create().min(0).build()),
    HEALING_POTION_AUTOPOT_POTENCY(6, DataValidatorBuilder.create().min(0).build()),
    HEALING_POTION_AUTOPOT_THRESHOLD(10, DataValidatorBuilder.create().min(0).build()),
    HEALING_POTION_AUTOPOT_HOTBAR_ONLY(true, DataValidatorBuilder.create().bool().build()),

    // Mana Potions
    MAX_MANA_POTIONS(7, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_POTION_CLICK_POTENCY(50, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_POTION_AUTOPOT_POTENCY(40, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_POTION_AUTOPOT_THRESHOLD(50, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_POTION_AUTOPOT_HOTBAR_ONLY(true, DataValidatorBuilder.create().bool().build()),

    // Mana
    MANA_MAX(100, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_REGENERATION_RATE(15, DataValidatorBuilder.create().integer().min(1).build()),
    MANA_REGENERATION_AMOUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_FINAL_BLOW_AMOUNT(25, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_ASSIST_AMOUNT(20, DataValidatorBuilder.create().integer().min(0).build()),
    MANA_DISPENSER_DISPENSE_AMOUNT(10, DataValidatorBuilder.create().integer().min(0).build()),

    // Minions
    VINDICATOR_MINION_TARGET_RADIUS(32, DataValidatorBuilder.create().min(0).build()),
    VINDICATOR_MINION_MEMORY(16, DataValidatorBuilder.create().integer().min(0).build()),

    // Aquaman
    AQUAMAN_WATER_SPHERE_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    AQUAMAN_WATER_SPHERE_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    AQUAMAN_ONE_WITH_THE_SEA_WATER_BREATHING_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    AQUAMAN_ONE_WITH_THE_SEA_WATER_BREATHING_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    AQUAMAN_ONE_WITH_THE_SEA_REGENERATION_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    AQUAMAN_ONE_WITH_THE_SEA_REGENERATION_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    AQUAMAN_TRIDENT_THROW_BASE_DAMAGE(5, DataValidatorBuilder.create().min(0).build()),
    AQUAMAN_TRIDENT_WATER_SYNERGY_DAMAGE_BONUS(4, DataValidatorBuilder.create().min(0).build()),
    AQUAMAN_TRIDENT_FAR_DISTANCE(35, DataValidatorBuilder.create().min(0).build()),
    AQUAMAN_TRIDENT_FAR_MULTIPLIER(2, DataValidatorBuilder.create().min(0).build()),
    AQUAMAN_TRIDENT_MISS_DELAY(100, DataValidatorBuilder.create().integer().min(0).build()),
    AQUAMAN_TRIDENT_LOYALTY_DELAY(20, DataValidatorBuilder.create().integer().min(0).build()),
    AQUAMAN_TRIDENT_MELEE_DAMAGE(5, DataValidatorBuilder.create().min(0).build()),
    AQUAMAN_TRIDENT_MELEE_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Aquarius
    AQUARIUS_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WAND_KNOCKBACK_LEVEL(1, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BEAM_MANA_COST(9, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BEAM_CAST_COOLDOWN(7, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BEAM_HEALING_POTENCY(2, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WATER_BEAM_POP_RADIUS(2.5, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WATER_BEAM_WET_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BEAM_MAX_RANGE(16, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WATER_BEAM_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WATER_BEAM_SPEED(4, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_CAST_COOLDOWN(2, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_MANA_COST(90, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_EXPLOSION_RADIUS(5, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WATER_BOMB_HEALING_TICKS(20, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_HEALING_TICK_RATE(2, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_HEALING_TICK_POTENCY(1, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_WATER_BOMB_POISON_DURATION(160, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_POISON_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    AQUARIUS_WATER_BOMB_NAUSEA_DURATION(160, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_NAUSEA_LEVEL(4, DataValidatorBuilder.create().integer().range(1, 256).build()),
    AQUARIUS_WATER_BOMB_WET_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_WATER_BOMB_VELOCITY_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    AQUARIUS_SOOTHING_WATER_HEALING_TICKS(8, DataValidatorBuilder.create().integer().min(0).build()),
    AQUARIUS_SOOTHING_WATER_HEALING_TICK_RATE(25, DataValidatorBuilder.create().integer().min(1).build()),
    AQUARIUS_SOOTHING_WATER_HEALING_POTENCY(1, DataValidatorBuilder.create().min(0).build()),

    // Archmage
    ARCHMAGE_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    ARCHMAGE_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Bomber
    BOMBER_BOMB_PLACE_MIN_DISTANCE(3, DataValidatorBuilder.create().min(0).build()),
    BOMBER_BOMB_COUNT(3, DataValidatorBuilder.create().integer().min(1).build()),
    BOMBER_BOMB_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    BOMBER_BOMB_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    BOMBER_BOMB_RADIUS(6, DataValidatorBuilder.create().range(0, 32).build()),
    BOMBER_BOMB_KNOCKBACK_MULTIPLIER(0.75, DataValidatorBuilder.create().min(0).build()),
    BOMBER_BOMB_REGENERATION_TICKS(160, DataValidatorBuilder.create().integer().min(1).build()),
    BOMBER_BOMB_DISPENSER_NUM(1, DataValidatorBuilder.create().integer().min(0).build()),
    BOMBER_DETONATE_FUSE_TICKS(30, DataValidatorBuilder.create().integer().min(0).build()),
    BOMBER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    BOMBER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Brute
    BRUTE_BERSERK_COOLDOWN(400, DataValidatorBuilder.create().integer().min(0).build()),
    BRUTE_BERSERK_DURATION(160, DataValidatorBuilder.create().integer().min(0).build()),
    BRUTE_BERSERK_ACTIVATION_THRESHOLD(10, DataValidatorBuilder.create().min(0).build()),
    BRUTE_BERSERK_MAX_STACKS(2, DataValidatorBuilder.create().integer().min(1).build()),
    BRUTE_AXE_SWIRL_COOLDOWN(60, DataValidatorBuilder.create().integer().min(0).build()),
    BRUTE_AXE_SWIRL_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    BRUTE_AXE_SWIRL_RADIUS(4, DataValidatorBuilder.create().min(0).build()),
    BRUTE_AXE_SWIRL_DELAY(5, DataValidatorBuilder.create().integer().min(0).build()),
    BRUTE_AXE_SWIRL_IGNORE_I_FRAMES(true, DataValidatorBuilder.create().bool().build()),
    BRUTE_AXE_MELEE_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    BRUTE_AXE_MELEE_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Buff Master
    BUFF_MASTER_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    BUFF_MASTER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    BUFF_MASTER_BUFF_RADIUS(5, DataValidatorBuilder.create().min(0).build()),
    BUFF_MASTER_BUFF_BASE_COOLDOWN(140, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_BUFF_MAX_COOLDOWN(300, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_BUFF_PER_PLAYER_COOLDOWN(40, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_BUFF_PER_MOB_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_ABSORPTION_DURATION(320, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_ABSORPTION_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    BUFF_MASTER_SPEED_DURATION(320, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_SPEED_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    BUFF_MASTER_RESISTANCE_DURATION(320, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_RESISTANCE_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    BUFF_MASTER_REGENERATION_DURATION(320, DataValidatorBuilder.create().integer().min(0).build()),
    BUFF_MASTER_REGENERATION_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    BUFF_MASTER_BUFF_SWITCH_ICD(2, DataValidatorBuilder.create().integer().min(0).build()),

    // Builder
    BUILDER_BRICKS_COUNT(32, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_BRICKS_FINAL_BLOW_REWARD(20, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_BRICKS_ASSIST_REWARD(10, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_BRICKS_REGENERATION_TICK_INTERVAL(50, DataValidatorBuilder.create().integer().min(1).build()),
    BUILDER_BRICKS_KNOCKBACK(3, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_BRICKS_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    BUILDER_BRICKS_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    BUILDER_BRICKS_REMOVE_COUNT_ON_MELEE(2, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_BRICKS_DISPENSER_NUM(10, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_LADDERS_COUNT(16, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_LADDERS_REGENERATION_TICK_INTERVAL(100, DataValidatorBuilder.create().integer().min(1).build()),
    BUILDER_LADDERS_FINAL_BLOW_REWARD(10, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_LADDERS_ASSIST_REWARD(5, DataValidatorBuilder.create().integer().min(0).build()),
    BUILDER_LADDERS_DISPENSER_NUM(5, DataValidatorBuilder.create().integer().min(0).build()),

    // Crusader
    CRUSADER_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SHIELD_BASH_DAMAGE(8, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SHIELD_BASH_KNOCKBACK(2, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SHIELD_BASH_COOLDOWN(160, DataValidatorBuilder.create().integer().min(0).build()),
    CRUSADER_SHIELD_BASH_IMPACT_CHECK_RADIUS(2, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SHIELD_BASH_COLLISION_HITBOX_EXPANSION(0.25, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SHIELD_BASH_VELOCITY_MULTIPLIER(1.25, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_SHIELD_BASH_IMPACT_ICD(50, DataValidatorBuilder.create().integer().min(0).build()),
    CRUSADER_SHIELD_BASH_VELOCITY_THRESHOLD(0.3, DataValidatorBuilder.create().min(0).build()),
    CRUSADER_IRONCLAD_DURATION(160, DataValidatorBuilder.create().integer().min(0).build()),
    CRUSADER_IRONCLAD_RESISTANCE_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),

    // Crusher
    CRUSHER_ANVIL_DIRECT_DAMAGE(12, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_INDIRECT_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_SUMMON_HEIGHT(6, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_SUMMON_RANGE(10, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_SUMMONING_ENTITY_HITBOX_SIZE(1, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_SUMMONING_BLOCK_HITBOX_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_IMPACT_RADIUS(3, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_DIRECT_IMPACT_RADIUS(1.5, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_STUN_RADIUS(1.5, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_STUN_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    CRUSHER_ANVIL_COOLDOWN(60, DataValidatorBuilder.create().integer().min(0).build()),
    CRUSHER_ANVIL_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_ANVIL_IGNORE_DAMAGE_TICKS(true, DataValidatorBuilder.create().bool().build()),
    CRUSHER_ANVIL_TARGET_ENEMIES(false, DataValidatorBuilder.create().bool().build()),
    CRUSHER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    CRUSHER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Default
    DEFAULT_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    DEFAULT_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Demolitionist
    DEMOLITIONIST_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    DEMOLITIONIST_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    DEMOLITIONIST_DEMOLISH_DAMAGE(12, DataValidatorBuilder.create().min(0).build()),
    DEMOLITIONIST_DEMOLISH_BOMB_FUSE_TICKS(100, DataValidatorBuilder.create().integer().min(0).build()),
    DEMOLITIONIST_DEMOLISH_BLOCKS_BROKEN_DURATION(400, DataValidatorBuilder.create().integer().min(0).build()),
    DEMOLITIONIST_DEMOLISH_COOLDOWN(600, DataValidatorBuilder.create().integer().min(0).build()),
    DEMOLITIONIST_DEMOLISH_RADIUS(12, DataValidatorBuilder.create().range(0, 32).build()),
    DEMOLITIONIST_DEMOLISH_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    DEMOLITIONIST_BOMB_RECYCLE_RADIUS(10, DataValidatorBuilder.create().min(0).build()),
    DEMOLITIONIST_FORCED_DEMOLITION_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    DEMOLITIONIST_INSTANT_DEMOLITION_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),

    // Demon
    MAX_BLOOD_POTIONS(7, DataValidatorBuilder.create().integer().min(0).build()),
    BLOOD_POTION_CLICK_POTENCY(10000, DataValidatorBuilder.create().integer().min(0).build()),
    BLOOD_POTION_AUTOPOT_POTENCY(8000, DataValidatorBuilder.create().integer().min(0).build()),
    BLOOD_POTION_AUTOPOT_THRESHOLD(10000, DataValidatorBuilder.create().integer().min(0).build()),
    BLOOD_POTION_AUTOPOT_HOTBAR_ONLY(true, DataValidatorBuilder.create().bool().build()),
    DEMON_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    DEMON_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    DEMON_ESSENCE_OF_THE_AFTER_LIFE_MAX(1, DataValidatorBuilder.create().integer().min(1).max(1).build()),
    DEMON_BLOOD_TO_HEALTH_CONVERSION(250, DataValidatorBuilder.create().integer().min(1).build()),
    DEMON_BLOOD_PER_ESSENCE(10000, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_BLOOD_MAX(50000, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_TRANSFUSION_SWITCH_MODE_COOLDOWN(10, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_TRANSFUSION_BLOOD_AMOUNT(150, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_TRANSFUSION_CONVERSION_RATE(4, DataValidatorBuilder.create().integer().min(1).build()),
    DEMON_HOMING_HEMOGLOBIN_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_COST(2500, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_SPEED(2, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_HOMING_FACTOR(1, DataValidatorBuilder.create().nonZero().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_PIERCING_LEVEL(0, DataValidatorBuilder.create().integer().range(1, 256).build()),
    DEMON_HOMING_HEMOGLOBIN_MAX_TRAVEL_DISTANCE(25, DataValidatorBuilder.create().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_START_HOMING_AFTER_DISTANCE(3, DataValidatorBuilder.create().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_START_HOMING_RADIUS(10, DataValidatorBuilder.create().min(0).build()),
    DEMON_HOMING_HEMOGLOBIN_DAMAGE(3, DataValidatorBuilder.create().min(0).build()),
    DEMON_BLOOD_BOND_TRANSMISSION_SPEED(0.1, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_BLOOD_BOND_BLOOD_MODE_TRANSMISSION_EFFICIENCY(75, DataValidatorBuilder.create().range(0, 100).build()),
    DEMON_BLOOD_BOND_HEALTH_MODE_TRANSMISSION_EFFICIENCY(25, DataValidatorBuilder.create().range(0, 100).build()),
    DEMON_BLOOD_BOND_HEALING_RATE(4, DataValidatorBuilder.create().integer().min(1).build()),
    DEMON_BLOOD_BOND_HEALING_POTENCY(0.6, DataValidatorBuilder.create().min(0).build()),
    DEMON_BLOOD_BOND_BREAK_DISTANCE(15, DataValidatorBuilder.create().min(0).build()),
    DEMON_HELLFIRE_BURN_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    DEMONS_CURSE_MAX_EFFECTIVE_BONDS(10, DataValidatorBuilder.create().integer().min(0).build()),
    DEMONS_CURSE_MAGIC_DAMAGE_INCREASE_PER_BLOOD_BOND(5, DataValidatorBuilder.create().min(0).build()),
    DEMONS_CURSE_PHYSICAL_DAMAGE_DECREASE_PER_BLOOD_BOND(10, DataValidatorBuilder.create().min(0).build()),
    DEMON_BREAK_BLOOD_BONDS_COST(0, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_BREAK_BLOOD_BONDS_COOLDOWN(10, DataValidatorBuilder.create().integer().min(0).build()),
    DEMON_BLOOD_BOND_BREAK_DAMAGE(1, DataValidatorBuilder.create().min(0).build()),

    // Engineer
    ENGINEER_SENTRY_WARMUP(200, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_SENTRY_FIRE_RATE(60, DataValidatorBuilder.create().integer().min(1).build()),
    ENGINEER_SENTRY_FIRE_RADIUS(20, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_SENTRY_LIMIT_RADIUS(16, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_SENTRY_PROJECTILE_SPEED(3, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_SENTRY_PROJECTILE_SIZE(0.01, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_SENTRY_PROJECTILE_PIERCE_LEVEL(0, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_SENTRY_PROJECTILE_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_SENTRY_METAL_COST(50, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_MAX_SENTRIES(2, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_SENTRY_HP(200, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_SENTRY_TARGETS_PER_SHOT(1, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_DISPENSER_DISPENSE_RATE(100, DataValidatorBuilder.create().integer().min(1).build()),
    ENGINEER_DISPENSER_DISPENSE_RADIUS(4, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_DISPENSER_LIMIT_RADIUS(6, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_DISPENSER_METAL_COST(70, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_MAX_DISPENSERS(1, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_DISPENSER_HP(300, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_DISPENSER_DISPENSE_METAL(10, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_DISPENSE_COOLDOWN_REFRESH_PERCENT(20, DataValidatorBuilder.create().range(0, 100).build()),
    ENGINEER_ENTRANCE_TELEPORTER_METAL_COST(25, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_ENTRANCE_TELEPORTER_HP(25, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_EXIT_TELEPORTER_METAL_COST(25, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_EXIT_TELEPORTER_HP(25, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_ENTRANCE_EXIT_MAX_DISTANCE(100, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_SATCHEL_MAX_METAL(200, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_KILL_ELIMINATION_REWARD(50, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_WRENCH_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_WRENCH_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    ENGINEER_WRENCH_REPAIR_METAL_AMOUNT(5, DataValidatorBuilder.create().integer().min(0).build()),
    ENGINEER_WRENCH_REPAIR_AMOUNT(25, DataValidatorBuilder.create().integer().min(0).build()),

    // Fish
    FISH_FISHPLOSION_VELOCITY_MULTIPLIER(1.25, DataValidatorBuilder.create().min(0).build()),
    FISH_FISHPLOSION_FISH_PER_LAYER(16, DataValidatorBuilder.create().integer().min(0).max(24).build()),
    FISH_FISHPLOSION_NUM_LAYERS(6, DataValidatorBuilder.create().integer().min(0).max(8).build()),
    FISH_FISHPLOSION_COOLDOWN(160, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_FISHPLOSION_SPREAD(0.1, DataValidatorBuilder.create().min(0).build()),
    FISH_TRAIL_INTERVAL(2, DataValidatorBuilder.create().integer().min(1).build()),
    FISH_COD_WEIGHT(500, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_COOKED_COD_WEIGHT(250, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_SALMON_WEIGHT(500, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_COOKED_SALMON_WEIGHT(250, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_TROPICAL_FISH_WEIGHT(50, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_PUFFERFISH_WEIGHT(1, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_TRAIL_HASTE_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_TRAIL_HASTE_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    FISH_TRAIL_SPEED_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_TRAIL_SPEED_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    FISH_TRAIL_WATER_BREATHING_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_TRAIL_WATER_BREATHING_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    FISH_OP_FISH_OUT_OF_WATER_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    FISH_OP_FISH_OUT_OF_WATER_DAMAGE_RATE(20, DataValidatorBuilder.create().integer().min(1).build()),
    FISH_THROW_ICD(6, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_THROW_OP_ICD(3, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_THROW_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    FISH_PUFFERFISH_DAMAGE(100, DataValidatorBuilder.create().min(0).build()),
    FISH_SALMON_DAMAGE(3, DataValidatorBuilder.create().min(0).build()),
    FISH_COOKED_SALMON_DAMAGE(5, DataValidatorBuilder.create().min(0).build()),
    FISH_TROPICAL_FISH_HEALING(1, DataValidatorBuilder.create().min(0).build()),
    FISH_CAN_ACTIVATE_OP_FISH(false, DataValidatorBuilder.create().bool().build()),
    FISH_BOW_FISH_PER_SHOT(1, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_BOW_OP_FISH_PER_SHOT(5, DataValidatorBuilder.create().integer().min(0).build()),
    FISH_MELEE_SPEED(5, DataValidatorBuilder.create().min(0).build()),
    FISH_MELEE_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    FISH_MELEE_SHARPNESS_LEVEL(1, DataValidatorBuilder.create().integer().min(0).build()),
    WATER_SYNERGY_LINGER_DURATION(20, DataValidatorBuilder.create().integer().min(0).build()),
    WATER_SYNERGY_DAMAGE_BONUS_PERCENTAGE(20, DataValidatorBuilder.create().min(0).build()),

    // Glacier
    GLACIER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    GLACIER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    GLACIER_ICE_BALL_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    GLACIER_ICE_BALL_VELOCITY_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    GLACIER_ICE_BALL_SLOWNESS_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    GLACIER_ICE_BALL_SLOWNESS_LEVEL(4, DataValidatorBuilder.create().integer().range(1, 256).build()),
    GLACIER_ICE_BALL_SNOW_LAYER_DURATION(500, DataValidatorBuilder.create().integer().min(0).build()),
    GLACIER_ICE_BALL_MAX_SNOW_LAYER(3, DataValidatorBuilder.create().integer().min(0).max(8).build()),
    GLACIER_SNOWDRIFT_DURATION(70, DataValidatorBuilder.create().integer().min(0).build()),
    GLACIER_SNOWDRIFT_SPEED_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    GLACIER_ICE_BALL_ENGINEER_BLOCK_STUN_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    GLACIER_ICE_BALL_ENGINEER_BLOCK_STUN_RADIUS(1, DataValidatorBuilder.create().min(0).build()),

    // Golem
    GOLEM_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    GOLEM_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    GOLEM_WAND_KNOCKBACK_LEVEL(1, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_WALL_MANA_COST(15, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_WALL_CAST_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_WALL_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_WALL_MAX_RANGE(16, DataValidatorBuilder.create().min(0).build()),
    GOLEM_EARTH_SHATTER_MANA_COST(60, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_SHATTER_CAST_COOLDOWN(40, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_SHATTER_ANGLE(70, DataValidatorBuilder.create().integer().min(0).max(360).build()),
    GOLEM_EARTH_SHATTER_SPEED(2, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_SHATTER_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    GOLEM_EARTH_SHATTER_RANGE(12, DataValidatorBuilder.create().min(0).build()),
    GOLEM_EARTH_SHATTER_HEIGHT(2, DataValidatorBuilder.create().min(0).build()),
    GOLEM_EARTH_SHATTER_FALL_HEIGHT(2.5, DataValidatorBuilder.create().min(0).build()),
    GOLEM_EARTH_SHATTER_MUST_CAST_ON_GROUND(true, DataValidatorBuilder.create().bool().build()),
    GOLEM_EARTH_SHATTER_ROOTING_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    GOLEM_EARTH_SHATTER_ROOTING_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),

    // Gunner
    GUNNER_BULLET_DAMAGE(2.5, DataValidatorBuilder.create().min(0).build()),
    GUNNER_FIRE_RATE(5, DataValidatorBuilder.create().integer().min(1).build()),
    GUNNER_OVERHEAT_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    GUNNER_OVERHEAT_PERCENTAGE_PER_SHOT(3.5, DataValidatorBuilder.create().min(0).build()),
    GUNNER_BULLET_VELOCITY_MULTIPLIER(3, DataValidatorBuilder.create().min(0).build()),
    GUNNER_REV_UP_ICD(16, DataValidatorBuilder.create().integer().min(0).build()),
    GUNNER_COOLING_RATE(1.67, DataValidatorBuilder.create().min(0).max(100).build()),
    GUNNER_BULLET_BLOCK_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    GUNNER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    GUNNER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Grappler
    GRAPPLER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    GRAPPLER_GRAPPLE_REEL_STRENGTH_MAX(2, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_REEL_STRENGTH_SCALAR(0.2, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_HOOK_HITBOX_EXPANSION(0.025, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_REEL_VOLUME_THRESHOLD(0.30, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_REEL_BELOW_DISTANCE(12, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_CAST_STRENGTH(1.5, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_FEATHER_FALLING_DAMAGE_REDUCTION(50, DataValidatorBuilder.create().min(0).max(100).build()),
    GRAPPLER_GRAPPLE_REEL_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    GRAPPLER_GRAPPLE_REEL_DAMAGE_IGNORE_NO_DAMAGE_TICKS(true, DataValidatorBuilder.create().bool().build()),
    GRAPPLER_GRAPPLE_REEL_DAMAGE_RESET_NO_DAMAGE_TICKS(true, DataValidatorBuilder.create().bool().build()),

    // Hitman
    HITMAN_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    HITMAN_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    HITMAN_BOW_MAX_DAMAGE(5, DataValidatorBuilder.create().min(0).build()),
    HITMAN_MAX_TAG_TRIGGERS(1, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_MAX_TAGS(6, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_GLOWING_DURATION(300, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_GLOWING_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    HITMAN_STUN_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_DARKNESS_DURATION(300, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_DARKNESS_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    HITMAN_WEAKNESS_DURATION(150, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_WEAKNESS_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    HITMAN_INSTANT_DAMAGE_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    HITMAN_ROTATE_EFFECT_COOLDOWN(2, DataValidatorBuilder.create().integer().min(0).build()),
    HITMAN_ACTIVATE_EFFECT_COOLDOWN(15, DataValidatorBuilder.create().integer().min(0).build()),

    // Hulk
    HULK_RAGE_FORM_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_FORM_MAX_COOLDOWN(900, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_FORM_MIN_COOLDOWN(150, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_FORM_SIZE(1, DataValidatorBuilder.create().min(0).build()),
    HULK_RELAX_FORM_SIZE(0.875, DataValidatorBuilder.create().min(0).build()),
    HULK_RAGE_FORM_DAMAGE_PERCENTAGE_BONUS(5, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_FORM_KILL_EXTENSION(200, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_FORM_ASSIST_EXTENSION(200, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_FORM_ACTIVATION_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    HULK_RAGE_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    HULK_RELAX_BOX_PUNCH(1, DataValidatorBuilder.create().integer().min(0).build()),
    HULK_RAGE_CHESTPLATE_ARMOR(8, DataValidatorBuilder.create().range(0, 30).build()),
    HULK_RAGE_CHESTPLATE_ARMOR_TOUGHNESS(2, DataValidatorBuilder.create().range(0, 20).build()),
    HULK_RAGE_CHESTPLATE_PROTECTION_LEVEL(2, DataValidatorBuilder.create().range(0, 10).build()),
    HULK_RAGE_CHESTPLATE_KNOCKBACK_RESISTANCE(0, DataValidatorBuilder.create().range(0, 1).build()),
    HULK_RAGE_LEGGINGS_ARMOR(6, DataValidatorBuilder.create().range(0, 30).build()),
    HULK_RAGE_LEGGINGS_ARMOR_TOUGHNESS(2, DataValidatorBuilder.create().range(0, 20).build()),
    HULK_RAGE_LEGGINGS_PROTECTION_LEVEL(2, DataValidatorBuilder.create().range(0, 10).build()),
    HULK_RAGE_LEGGINGS_KNOCKBACK_RESISTANCE(0, DataValidatorBuilder.create().range(0, 1).build()),
    HULK_RAGE_BOOTS_ARMOR(3, DataValidatorBuilder.create().range(0, 30).build()),
    HULK_RAGE_BOOTS_ARMOR_TOUGHNESS(2, DataValidatorBuilder.create().range(0, 20).build()),
    HULK_RAGE_BOOTS_PROTECTION_LEVEL(2, DataValidatorBuilder.create().range(0, 10).build()),
    HULK_RAGE_BOOTS_KNOCKBACK_RESISTANCE(0, DataValidatorBuilder.create().range(0, 1).build()),

    // Illusionist
    ILLUSIONIST_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_DAMAGE_PERCENTAGE_INCREASE(10, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_BLOCK_HACK_DURATION(250, DataValidatorBuilder.create().integer().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_BLOCK_HACK_RADIUS(2, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_TAG_DURATION(150, DataValidatorBuilder.create().integer().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_THROW_MULTIPLIER(2, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_FUTURE_SIGHT_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_DIVINATION_STAR_DO_DISORIENTATION(false, DataValidatorBuilder.create().bool().build()),
    ILLUSIONIST_FAKE_DEATH_COOLDOWN(600, DataValidatorBuilder.create().integer().min(0).build()),
    ILLUSIONIST_FAKE_DEATH_INVISIBILITY_DURATION(300, DataValidatorBuilder.create().integer().min(0).build()),
    ILLUSIONIST_FAKE_DEATH_INITIAL_PUSH_BACK_MULTIPLIER(2, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_FAKE_DEATH_HEALING(20, DataValidatorBuilder.create().min(0).build()),
    ILLUSIONIST_FAKE_DEATH_UNCLOAK_HACK_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),

    // Jumper
    JUMPER_SWORD_DAMAGE(8, DataValidatorBuilder.create().min(0).build()),
    JUMPER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    JUMPER_TRANSLOCATOR_PICKUP_DELAY(20, DataValidatorBuilder.create().integer().min(0).build()),
    JUMPER_TRANSLOCATOR_THROW_MULTIPLIER(1.5, DataValidatorBuilder.create().min(0).build()),
    JUMPER_TRANSLOCATOR_TELEPORT_DISTANCE(60, DataValidatorBuilder.create().min(0).build()),
    JUMPER_TRANSLOCATOR_LIFE_DURATION(24000, DataValidatorBuilder.create().integer().min(0).build()),
    JUMPER_TRANSLOCATOR_SILENT_TELEPORT(false, DataValidatorBuilder.create().bool().build()),
    JUMPER_TRANSLOCATOR_AFTER_THROW_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    JUMPER_TRANSLOCATOR_AFTER_PICKUP_COOLDOWN(40, DataValidatorBuilder.create().integer().min(0).build()),
    JUMPER_TRANSLOCATOR_AFTER_RECOVER_COOLDOWN(80, DataValidatorBuilder.create().integer().min(0).build()),
    JUMPER_TRANSLOCATOR_AFTER_USE_COOLDOWN(300, DataValidatorBuilder.create().integer().min(0).build()),
    JUMPER_TRANSLOCATOR_AFTER_DESTROY_COOLDOWN(300, DataValidatorBuilder.create().integer().min(0).build()),

    // Kangaroo
    KANGAROO_STOMP_COOLDOWN(210, DataValidatorBuilder.create().integer().min(0).build()),
    KANGAROO_STOMP_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    KANGAROO_STOMP_JUMPBOOST_LEVEL(5, DataValidatorBuilder.create().integer().range(1, 256).build()),
    KANGAROO_STOMP_HEIGHT_THRESHOLD(3.5, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_STOMP_MIN_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_STOMP_MAX_DAMAGE(30, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_STOMP_RAMP_UP_START(5, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_STOMP_RAMP_UP_END(50, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_STOMP_RADIUS(3.5, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    KANGAROO_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Knight
    KNIGHT_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    KNIGHT_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    KNIGHT_FORTIFY_SHIELD_DAMAGE_PERCENTAGE(75, DataValidatorBuilder.create().min(0).build()),
    KNIGHT_ROYAL_GUARD_REDIRECTED_DAMAGE_PERCENTAGE(50, DataValidatorBuilder.create().range(0, 100).build()),
    KNIGHT_DAMAGE_DEFLECTION_PERCENTAGE(50, DataValidatorBuilder.create().min(0).build()),
    KNIGHT_FORTIFY_COOLDOWN(300, DataValidatorBuilder.create().integer().min(0).build()),
    KNIGHT_FORTIFY_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    KNIGHT_FORTIFY_RADIUS(8, DataValidatorBuilder.create().min(0).build()),
    KNIGHT_FORTIFY_RESET_SHIELD_DURABILITY(true, DataValidatorBuilder.create().bool().build()),

    // Master
    MASTER_MINIONS_MAX_CREEPERS(4, DataValidatorBuilder.create().integer().min(0).build()),
    MASTER_MINIONS_SPAWN_CREEPER_COOLDOWN(80, DataValidatorBuilder.create().integer().min(0).build()),
    MASTER_MINIONS_SPAWN_CREEPER_AMOUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    MASTER_MINIONS_CREEPER_DURATION(1200, DataValidatorBuilder.create().integer().min(0).build()),
    MASTER_MINIONS_CREEPER_DAMAGE(9, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINIONS_CHARGED_CREEPER_DAMAGE(12, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINIONS_CREEPER_MAX_HEALTH(8, DataValidatorBuilder.create().range(1, 1024).build()),
    MASTER_MINIONS_CREEPER_EXPLOSION_RADIUS(5, DataValidatorBuilder.create().range(0, 32).build()),
    MASTER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    MASTER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_TARGET_RADIUS(16, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_MEMORY(5, DataValidatorBuilder.create().integer().min(0).build()),
    MASTER_MINION_START_RETURN_TO_ANCHOR_DISTANCE(32, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_END_RETURN_TO_ANCHOR_DISTANCE(16, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_WALKING_BACK_SPEED(1.25, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_START_FOLLOW_OWNER_DISTANCE(6, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_END_FOLLOW_OWNER_DISTANCE(3, DataValidatorBuilder.create().min(0).build()),
    MASTER_MINION_FOLLOW_OWNER_SPEED(1, DataValidatorBuilder.create().min(0).build()),

    // Mathematician
    MATHEMATICIAN_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    MATHEMATICIAN_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    MATHEMATICIAN_PRACTICE_PROBLEMS_DURATION(12000, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_PRACTICE_PROBLEMS_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    MATHEMATICIAN_PRACTICE_PROBLEMS_ALLY_HEALING(6, DataValidatorBuilder.create().min(0).build()),
    MATHEMATICIAN_PRACTICE_PROBLEMS_ENEMY_HEALING(4, DataValidatorBuilder.create().min(0).build()),
    MATHEMATICIAN_PRACTICE_PROBLEMS_MAX_ARGUMENT_MAGNITUDE(12, DataValidatorBuilder.create().integer().build()),
    MATHEMATICIAN_WORKSHEETS_PER_PLAYER(15, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_COUNT(20, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_REGENERATION_RATE(15, DataValidatorBuilder.create().integer().min(1).build()),
    MATHEMATICIAN_WORKSHEET_THROW_COOLDOWN(2, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_PRACTICE_PROBLEMS_GENERATE_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_EFFECT_DURATION(600, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_EFFECT_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    MATHEMATICIAN_WORKSHEET_VELOCITY_MULTIPLIER(2, DataValidatorBuilder.create().min(0).build()),
    MATHEMATICIAN_WORKSHEET_DISTRIBUTE_INCREMENT_AMOUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_DISTRIBUTE_DECREMENT_AMOUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_DISPENSE_AMOUNT(10, DataValidatorBuilder.create().integer().min(0).build()),
    MATHEMATICIAN_WORKSHEET_ELIMINATION_REWARD(20, DataValidatorBuilder.create().integer().min(0).build()),

    // Medic
    MEDIC_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    MEDIC_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    MEDIC_HEALING_STONE_POTENCY(1, DataValidatorBuilder.create().min(0).build()),
    MEDIC_MAX_ELECTROLYTES(12, DataValidatorBuilder.create().min(0).build()),
    MEDIC_HEALING_STONE_RADIUS(6, DataValidatorBuilder.create().min(0).build()),
    MEDIC_HEALING_STONE_HEAL_RATE(2, DataValidatorBuilder.create().integer().min(1).build()),
    MEDIC_HEALING_STONE_SELF_HEAL_RATE(10, DataValidatorBuilder.create().integer().min(1).build()),
    MEDIC_ELECTROLYTES_REGENERATION_RATE(1, DataValidatorBuilder.create().integer().min(1).build()),
    MEDIC_ELECTROLYTES_REGENERATION_AMOUNT(0.15, DataValidatorBuilder.create().min(0).build()),
    MEDIC_POTION_SHARE_RADIUS(6, DataValidatorBuilder.create().min(0).build()),
    MEDIC_POTION_SHARE_POTENCY(5, DataValidatorBuilder.create().min(0).build()),

    // Mercy
    MERCY_STAFF_MELEE_DAMAGE(2, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_MELEE_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_MELEE_KNOCKBACK(1, DataValidatorBuilder.create().integer().min(0).build()),
    MERCY_STAFF_BEAM_RANGE(15, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_HEAL_POTENCY(2, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_HEAL_RATE(10, DataValidatorBuilder.create().integer().min(1).build()),
    MERCY_STAFF_DAMAGING_AMOUNT(1.5, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_DAMAGING_RATE(20, DataValidatorBuilder.create().integer().min(1).build()),
    MERCY_STAFF_DAMAGE_BUFF_PERCENTAGE(20, DataValidatorBuilder.create().integer().min(0).build()),
    MERCY_STAFF_DAMAGE_NERF_PERCENTAGE(20, DataValidatorBuilder.create().integer().min(0).build()),
    MERCY_SWITCH_MODE_COOLDOWN(10, DataValidatorBuilder.create().integer().min(0).build()),
    MERCY_STAFF_LINE_OF_SIGHT_THRESHOLD(100, DataValidatorBuilder.create().integer().min(0).build()),
    MERCY_STAFF_ATTACH_CHECK_RANGE(8, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_ATTACH_CHECK_SIZE(0.25, DataValidatorBuilder.create().min(0).build()),
    MERCY_STAFF_USE_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    MERCY_STAFF_MAX_CONNECTIONS(3, DataValidatorBuilder.create().integer().range(1, 32).build()),

    // Miner
    MINER_MINERS_FERVOR_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    MINER_MINERS_FERVOR_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    MINER_MINERS_FERVOR_HASTE_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    MINER_MINERS_FERVOR_GOBBLESTONE_PER_MELEE_HIT_MULTIPLIER(1.15, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_ENGINEER_BLOCK_DAMAGE_ADDITIVE(50, DataValidatorBuilder.create().integer().min(0).build()),
    MINER_PAXEL_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    MINER_PAXEL_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    MINER_UPGRADED_PAXEL_EFFICIENCY_LEVEL(4, DataValidatorBuilder.create().integer().min(0).build()),
    MINER_GOBBLESTONE_MAX(8, DataValidatorBuilder.create().integer().range(1, 1024).build()),
    MINER_GOBBLESTONE_PER_BLOCK_BREAK(0.5, DataValidatorBuilder.create().nonZero().build()),
    MINER_GOBBLESTONE_PER_ENGINEER_BLOCK_HIT(0.5, DataValidatorBuilder.create().nonZero().build()),
    MINER_GOBBLESTONE_PER_BEACON_HIT(2, DataValidatorBuilder.create().nonZero().build()),
    MINER_GOBBLESTONE_GIVE_COOLDOWN(5, DataValidatorBuilder.create().integer().min(1).build()),
    MINER_GOBBLESTONE_THROW_COOLDOWN(20, DataValidatorBuilder.create().nonZero().integer().min(1).build()),
    MINER_GOBBLESTONE_THROW_COUNT(1, DataValidatorBuilder.create().min(1).nonZero().build()),
    MINER_GOBBLESTONE_THROW_SPEED(1, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_GOBBLESTONE_THROW_SPREAD(0, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_GOBBLESTONE_BURST_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    MINER_GOBBLESTONE_BURST_COUNT(8, DataValidatorBuilder.create().min(1).nonZero().build()),
    MINER_GOBBLESTONE_BURST_SPEED(0.5, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_GOBBLESTONE_BURST_SPREAD(0.35, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_GOBBLESTONE_BURST_RATE(4, DataValidatorBuilder.create().nonZero().integer().min(1).build()),
    MINER_GOBBLESTONE_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_GOBBLESTONE_DAMAGE(4, DataValidatorBuilder.create().min(0).nonZero().build()),
    MINER_GOBBLESTONE_EXPLODE_RADIUS(3, DataValidatorBuilder.create().range(0, 64).build()),
    MINER_GOBBLESTONE_IGNORE_NO_DAMAGE_TICKS(true, DataValidatorBuilder.create().bool().build()),
    MINER_GOBBLESTONE_SIZE(1, DataValidatorBuilder.create().range(0, 64).nonZero().build()),


    // Musketeer
    MUSKETEER_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_MAX_AMMO(180, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_HEAVY_BULLET(false, DataValidatorBuilder.create().bool().build()),
    MUSKETEER_RIFLE_MAGAZINE_SIZE(18, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_AMMO_DISPENSER_DISPENSE_AMOUNT(9, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_AMMO_FINAL_BLOW_REWARD(36, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_AMMO_ASSIST_REWARD(18, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_LEFT_CLICK_ACTION_ICD(5, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_SHOOT_COOLDOWN(30, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_RELOAD_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_FALLOFF_DISTANCE_START(100, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_FALLOFF_DISTANCE_END(150, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_DAMAGE(10, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_SPEED(0, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_PIERCING_LEVEL(2, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_BLOCK_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_AMMO_CONSUMPTION_PER_SHOT(3, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_SNIPER_MODE_BULLET_IGNORE_I_FRAMES(false, DataValidatorBuilder.create().bool().build()),
    MUSKETEER_RIFLE_BURST_MODE_SHOOT_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_RELOAD_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_FALLOFF_DISTANCE_START(6, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_FALLOFF_DISTANCE_END(12, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_SPEED(25, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_PIERCING_LEVEL(0, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_BLOCK_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_AMMO_CONSUMPTION_PER_SHOT(1, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_BULLET_IGNORE_I_FRAMES(true, DataValidatorBuilder.create().bool().build()),
    MUSKETEER_RIFLE_BURST_MODE_DELAY_BETWEEN_SHOTS(4, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_BURST_MODE_NUMBER_OF_SHOTS(3, DataValidatorBuilder.create().integer().min(0).build()),
    MUSKETEER_RIFLE_DO_GLOWING_ON_BULLET_HIT(false, DataValidatorBuilder.create().bool().build()),
    MUSKETEER_RIFLE_BULLET_GLOWING_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),

    // Necromancer
    NECROMANCER_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_SWORD_WITHER_EFFECT_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    NECROMANCER_SWORD_WITHER_EFFECT_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_ESSENCE_OF_THE_AFTER_LIFE_MAX(15, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_ESSENCE_OF_THE_AFTER_LIFE_FINAL_BLOW_DROP_BONUS(0, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_ESSENCE_OF_THE_AFTER_LIFE_PLAYER_DROP_COUNT_PERCENTAGE(100, DataValidatorBuilder.create().range(0, 100).build()),
    NECROMANCER_WITHER_SKELETON_ESSENCE_PER_SKELETON(1, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_DURATION(12000, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_STONE_SWORD_DAMAGE(5, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_1_BASE_HEALTH(20, DataValidatorBuilder.create().range(1, 1024).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_1_BASE_DEFENSE_POINTS(10, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_1_SPEED_INCREASE_PERCENTAGE(25, DataValidatorBuilder.create().range(0, 100).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_2_CHESTPLATE_DEFENSE_POINTS(2, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_2_LEGGINGS_DEFENSE_POINTS(1, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_2_BOOTS_DEFENSE_POINTS(2, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_3_HEALTH_INCREASE(20, DataValidatorBuilder.create().range(1, 1024).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_4_CHESTPLATE_DEFENSE_POINTS(4, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_4_LEGGINGS_DEFENSE_POINTS(2, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_4_BOOTS_DEFENSE_POINTS(4, DataValidatorBuilder.create().range(1, 30).build()),
    NECROMANCER_WITHER_SKELETON_LEVEL_5_KNOCK_BACK_RESISTANCE_PERCENTAGE(75, DataValidatorBuilder.create().range(0, 100).build()),
    NECROMANCER_WITHER_SKELETON_ESSENCE_DROP_COUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_ESSENCE_HEAL_COST(1, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_ESSENCE_UPGRADE_COST(1, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_HEAL_SKELETON_POTENCY(10, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_WITHER_SKELETON_HEAL_SKELETON_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_UPGRADE_SKELETON_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_PICKUP_SKELETON_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_SPAWN_SKELETON_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_DEATH_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_WITHER_SKELETON_WITHER_EFFECT_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    NECROMANCER_WITHER_SKELETON_WITHER_EFFECT_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_MINION_TARGET_RADIUS(16, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_MINION_MEMORY(8, DataValidatorBuilder.create().integer().min(0).build()),
    NECROMANCER_MINION_START_FOLLOW_OWNER_DISTANCE(10, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_MINION_END_FOLLOW_OWNER_DISTANCE(5, DataValidatorBuilder.create().min(0).build()),
    NECROMANCER_MINION_FOLLOW_OWNER_SPEED(1.25, DataValidatorBuilder.create().min(0).build()),

    // Ninja
    NINJA_KATANA_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    NINJA_KATANA_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    NINJA_KI_MAX(60, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_KI_PER_MELEE_ATTACK(5, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_KI_TO_DAMAGE_RATIO(1, DataValidatorBuilder.create().nonZero().min(0).build()),
    NINJA_KI_PARRY_CONSUME_AMOUNT(60, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_KI_SWORDS_TO_DISPLAY(5, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_KI_ELIMINATION_REWARD(5, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_PARRY_DURATION(20, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_PARRY_COOLDOWN(80, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_PARRY_BASE_DAMAGE_PERCENTAGE(50, DataValidatorBuilder.create().min(0).build()),
    NINJA_PARRY_DAMAGE_INCREASE_PER_KI(5, DataValidatorBuilder.create().min(0).build()),
    NINJA_PARRY_DAMAGE_RADIUS(6, DataValidatorBuilder.create().min(0).build()),
    NINJA_PARRY_IGNORE_I_FRAMES(true, DataValidatorBuilder.create().bool().build()),
    NINJA_DODGE_COOLDOWN(600, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_DODGE_MIN_RADIUS(12, DataValidatorBuilder.create().min(0).build()),
    NINJA_DODGE_MAX_RADIUS(25, DataValidatorBuilder.create().min(0).build()),
    NINJA_DODGE_AROUND_ENEMY_TARGET_RADIUS(8, DataValidatorBuilder.create().min(0).build()),
    NINJA_DODGE_AROUND_ENEMY_COOLDOWN(80, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_DODGE_MIN_RADIUS_AROUND_ENEMY(3, DataValidatorBuilder.create().min(0).build()),
    NINJA_DODGE_MAX_RADIUS_AROUND_ENEMY(4, DataValidatorBuilder.create().min(0).build()),
    NINJA_DODGE_USE_IN_COMBAT_KI_BONUS(5, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_AGILITY_SPEED_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    NINJA_AGILITY_SPEED_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),

    // None
    NONE_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    NONE_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Porcupine
    PORCUPINE_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    PORCUPINE_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    PORCUPINE_QUILL_DAMAGE(8, DataValidatorBuilder.create().min(0).build()),
    PORCUPINE_QUILL_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    PORCUPINE_QUILL_SPEED(0.75, DataValidatorBuilder.create().min(0).build()),
    PORCUPINE_QUILL_SPREAD(0.2, DataValidatorBuilder.create().min(0).build()),
    PORCUPINE_QUILL_ARROWS_PER_LAYER(16, DataValidatorBuilder.create().integer().range(0, 32).build()),
    PORCUPINE_QUILL_NUMBER_OF_LAYERS(7, DataValidatorBuilder.create().integer().range(0, 12).build()),
    PORCUPINE_QUILL_STUN_DURATION(15, DataValidatorBuilder.create().integer().min(0).build()),
    PORCUPINE_QUILL_POISON_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    PORCUPINE_QUILL_POISON_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    PORCUPINE_QUILL_SLOWNESS_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    PORCUPINE_QUILL_SLOWNESS_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    PORCUPINE_THORNS_DURATION(160, DataValidatorBuilder.create().integer().min(0).build()),
    PORCUPINE_THORNS_HIT_CHANCE_PERCENTAGE(40, DataValidatorBuilder.create().range(0, 100).build()),
    PORCUPINE_THORNS_HIT_RADIUS(12, DataValidatorBuilder.create().min(0).build()),
    PORCUPINE_THORNS_CHECK_LOS(false, DataValidatorBuilder.create().bool().build()),
    PORCUPINE_THORNS_DAMAGE_PERCENTAGE(50, DataValidatorBuilder.create().min(0).build()),

    // Potion Master
    POTION_MASTER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    POTION_MASTER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_COOLDOWN(80, DataValidatorBuilder.create().integer().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_VELOCITY_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_HARMING_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    POTION_MASTER_THROWABLE_POTION_HARMING_DURATION(5, DataValidatorBuilder.create().integer().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_SLOWNESS_LEVEL(3, DataValidatorBuilder.create().integer().range(1, 256).build()),
    POTION_MASTER_THROWABLE_POTION_SLOWNESS_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_POISON_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    POTION_MASTER_THROWABLE_POTION_POISON_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_WEAKNESS_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    POTION_MASTER_THROWABLE_POTION_WEAKNESS_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    POTION_MASTER_THROWABLE_POTION_CYCLE_ON_HIT(true, DataValidatorBuilder.create().bool().build()),

    // Priest
    PRIEST_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    PRIEST_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    PRIEST_WAND_KNOCKBACK(1, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_LIGHT_BEAM_MANA_COST(12, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_LIGHT_BEAM_CAST_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_LIGHT_BEAM_MAX_RANGE(30, DataValidatorBuilder.create().min(0).build()),
    PRIEST_LIGHT_BEAM_SPEED(0, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_LIGHT_BEAM_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    PRIEST_LIGHT_BEAM_ABSORPTION_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    PRIEST_LIGHT_BEAM_ABSORPTION_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_LIGHT_BEAM_GLOWING_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    PRIEST_LIGHT_BEAM_GLOWING_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_SOOTHING_LIGHT_HEALING_TICKS(8, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_SOOTHING_LIGHT_HEALING_TICK_RATE(20, DataValidatorBuilder.create().integer().min(1).build()),
    PRIEST_SOOTHING_LIGHT_HEALING_POTENCY(1, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_MANA_COST(20, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_COOLDOWN(10, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_HEALING_MIN(3, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_HEALING_PER_GRACE(0.34, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_1_GRACE(10, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_2_GRACE(20, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_3_GRACE(30, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_4_GRACE(40, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_5_GRACE(50, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_0_RADIUS(10, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_2_RADIUS(15, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_2_BURN_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_4_RADIUS(20, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_4_KNOCKBACK_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_4_KNOCKBACK_Y(0, DataValidatorBuilder.create().min(0).build()),
    PRIEST_ABSOLUTION_LEVEL_5_ABSORPTION_LEVEL(5, DataValidatorBuilder.create().integer().range(1, 256).build()),
    PRIEST_ABSOLUTION_LEVEL_5_ABSORPTION_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_GRACE_MAX(50, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_GRACE_FINAL_BLOW_REWARD(5, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_GRACE_ASSIST_REWARD(1, DataValidatorBuilder.create().integer().min(0).build()),
    PRIEST_GRACE_PER_LIGHT_BEAM_HIT(2, DataValidatorBuilder.create().integer().min(0).build()),

    // Prometheus
    PROMETHEUS_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_WAND_KNOCKBACK(1, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FLAME_MANA_COST(5, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FLAME_CAST_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FLAME_RANGE(7, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FLAME_SPEED(3, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FLAME_BLOCK_HITBOX_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FLAME_ENTITY_HITBOX_SIZE(1, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FLAME_BURN_DURATION(60, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FIREBALL_MANA_COST(50, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FIREBALL_CAST_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FIREBALL_HIT_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FIREBALL_EXPLOSION_RADIUS(5, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FIREBALL_EXPLOSION_DAMAGE(10, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FIREBALL_EXPLOSION_IGNORE_I_FRAMES(true, DataValidatorBuilder.create().bool().build()), // Increase the hit damage when changing this to false
    PROMETHEUS_FIREBALL_EXPLOSION_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_FIREBALL_EXPLOSION_FIRE_DURATION(120, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_FIREBALL_EXPLOSION_KNOCKBACK_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    PROMETHEUS_IMBUE_MANA_COST(100, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_IMBUE_CAST_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_IMBUE_FIRE_ASPECT_LEVEL(2, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_IMBUE_FIRE_RESISTANCE_LEVEL(5, DataValidatorBuilder.create().integer().range(1, 256).build()),
    PROMETHEUS_IMBUE_DURATION(900, DataValidatorBuilder.create().integer().min(0).build()),
    PROMETHEUS_IMBUE_SELF_DAMAGE(69, DataValidatorBuilder.create().min(0).build()),

    // Pyrotechnic
    PYROTECHNIC_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_MAX_AMMO(8, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_AMMO_REGENERATION_RATE(60, DataValidatorBuilder.create().integer().min(1).build()),
    PYROTECHNIC_AMMO_REGENERATION_COUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_AMMO_DISPENSER_DISPENSE_AMOUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_AMMO_ASSIST_REWARD(1, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_AMMO_FINAL_BLOW_REWARD(3, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_ROCKET_AMMO_CONSUMPTION(1, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_ROCKET_SHOOT_COOLDOWN(30, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_ROCKET_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_ROCKET_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_ROCKET_RADIUS(3, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_ROCKET_KNOCKBACK_MULTIPLIER(0.35, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_ROCKET_RECOIL_MULTIPLIER(0.05, DataValidatorBuilder.create().min(0).build()),
    PYROTECHNIC_BARRAGE_LOAD_ROCKETS_WHEN_ACTIVATING(true, DataValidatorBuilder.create().bool().build()),
    PYROTECHNIC_BARRAGE_COOLDOWN(400, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_BARRAGE_DURATION(120, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_BARRAGE_ROCKET_AMMO_CONSUMPTION(1, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_BARRAGE_ROCKET_SHOOT_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    PYROTECHNIC_BARRAGE_ROCKETS_PER_SHOT(3, DataValidatorBuilder.create().integer().min(0).build()),

    // Raven
    RAVEN_SWORD_DAMAGE(8, DataValidatorBuilder.create().min(0).build()),
    RAVEN_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    RAVEN_WAND_KNOCKBACK(1, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_WIND_GUST_MANA_COST(40, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_WIND_GUST_CAST_COOLDOWN(50, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_WIND_GUST_STRENGTH(3, DataValidatorBuilder.create().min(0).build()),
    RAVEN_WIND_GUST_SPEED(5, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_WIND_GUST_RANGE(15, DataValidatorBuilder.create().min(0).build()),
    RAVEN_WIND_GUST_DAMAGE(1, DataValidatorBuilder.create().min(0).build()),
    RAVEN_WIND_GUST_BLOCK_HITBOX_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    RAVEN_WIND_GUST_ENTITY_HITBOX_SIZE(1.5, DataValidatorBuilder.create().min(0).build()),
    RAVEN_FLIGHT_MANA_CAST_COST(0, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_FLIGHT_CAST_COOLDOWN(5, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_FLIGHT_ACTIVE_MANA_COST(8, DataValidatorBuilder.create().integer().min(0).build()),
    RAVEN_FLIGHT_TICK_RATE(20, DataValidatorBuilder.create().integer().min(1).build()),
    RAVEN_FLIGHT_SPEED(0.04, DataValidatorBuilder.create().min(0).build()),
    RAVEN_FLIGHT_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    RAVEN_FLIGHT_STUNNED_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),

    // Slime
    SLIME_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    SLIME_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SLIME_MINION_HEALTH(14, DataValidatorBuilder.create().range(1, 1024).build()),
    SLIME_MINION_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    SLIME_MINION_DURATION(400, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_MINION_SUMMON_COOLDOWN(75, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_MINION_MAX_MINIONS(3, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_MINION_ABSORPTION_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SLIME_MINION_ABSORPTION_DURATION(400, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_MINION_ABSORPTION_RADIUS(5, DataValidatorBuilder.create().min(0).build()),
    SLIME_ARMOR_DURATION(200, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_ARMOR_LEVEL(2, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SLIME_ARMOR_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_ARMOR_APPLY_RADIUS(7, DataValidatorBuilder.create().min(0).build()),
    SLIME_MINION_TARGET_RADIUS(8, DataValidatorBuilder.create().min(0).build()),
    SLIME_MINION_MEMORY(1, DataValidatorBuilder.create().integer().min(0).build()),
    SLIME_ATTACK_RADIUS(2.25, DataValidatorBuilder.create().min(0).build()),

    // Sniper
    SNIPER_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    SNIPER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SNIPER_ARROWS_MAX(8, DataValidatorBuilder.create().integer().min(0).build()),
    SNIPER_ARROWS_REGENERATION_RATE(160, DataValidatorBuilder.create().integer().min(1).build()),
    SNIPER_ARROWS_DISPENSER_DISPENSE_COUNT(2, DataValidatorBuilder.create().integer().min(0).build()),
    SNIPER_ARROWS_FINAL_BLOW_REWARD(2, DataValidatorBuilder.create().integer().min(0).build()),
    SNIPER_ARROWS_ASSIST_REWARD(1, DataValidatorBuilder.create().integer().min(0).build()),
    SNIPER_INFINITY_BOW_HEADSHOT_PERCENTAGE_INCREASE(25, DataValidatorBuilder.create().min(0).build()),
    SNIPER_POWER_BOW_DAMAGE_PERCENTAGE_INCREASE(25, DataValidatorBuilder.create().min(0).build()),
    SNIPER_POWER_BOW_PUNCH_LEVEL(2, DataValidatorBuilder.create().integer().min(0).build()),
    SNIPER_POWER_BOW_KNEE_SHOT_SLOWNESS_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SNIPER_POWER_BOW_KNEE_SHOT_SLOWNESS_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    SNIPER_POWER_BOW_USE_LAST_ARROW(false, DataValidatorBuilder.create().bool().build()),

    // Snow Golem
    SNOW_GOLEM_ICICLE_STAFF_MELEE_DAMAGE(4, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_MELEE_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_SPEED(3, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_MAX_RANGE(32, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_PIERCING_LEVEL(0, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_DAMAGE(2, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_HEALING(2, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_ICICLE_STAFF_PROJECTILE_COOLDOWN(25, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_SPAWN_COOLDOWN(160, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_MAX_GOLEMS(2, DataValidatorBuilder.create().integer().range(0, 64).build()),
    SNOW_GOLEM_MINION_SPAWN_GOLEM_AMOUNT(1, DataValidatorBuilder.create().integer().range(1, 64).build()),
    SNOW_GOLEM_MINION_GOLEMS_DURATION(2400, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_GOLEMS_MAX_HEALTH(12, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_DAMAGE(2, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_TARGET_RADIUS(16, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_MEMORY(12, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_START_FOLLOW_OWNER_DISTANCE(12, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_END_FOLLOW_OWNER_DISTANCE(6, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_FOLLOW_OWNER_SPEED(1.25, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_ATTACK_COOLDOWN(25, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_PREFERRED_ATTACK_DISTANCE(10, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_MINIMUM_TARGET_DURATION(50, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_SNOW_LAYER_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MAX_SNOW_LAYERS(1, DataValidatorBuilder.create().integer().min(0).max(8).build()),
    SNOW_GOLEM_MINION_ICICLE_STAFF_PROJECTILE_SPEED(3, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_STAFF_PROJECTILE_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_STAFF_PROJECTILE_MAX_RANGE(32, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_STAFF_PROJECTILE_PIERCING_LEVEL(0, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_PROJECTILE_DAMAGE(2, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_MINION_ICICLE_PROJECTILE_HEALING(2, DataValidatorBuilder.create().min(0).build()),
    SNOW_GOLEM_SNOW_MINION_FIRE_DAMAGE_WEAKNESS_PERCENTAGE(20, DataValidatorBuilder.create().build()),
    SNOW_GOLEM_SNOW_MINION_ICE_DAMAGE_RESISTANCE_PERCENTAGE(20, DataValidatorBuilder.create().build()),
    SNOW_GOLEM_SNOW_TRAIL_SUPPORT_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),
    SNOW_GOLEM_SNOW_TRAIL_SUPPORT_HEALING_PER_SECOND(1, DataValidatorBuilder.create().min(1).build()),
    SNOW_GOLEM_ICICLE_SHOULD_CREATE_SNOW_LAYER_ON_ENTITY_HIT(true, DataValidatorBuilder.create().bool().build()),
    SNOW_GOLEM_ICICLE_SHOULD_IGNORE_NO_DAMAGE_TICKS(true, DataValidatorBuilder.create().bool().build()),
    SNOW_GOLEM_ICICLE_SHOULD_RESET_NO_DAMAGE_TICKS(true, DataValidatorBuilder.create().bool().build()),

    // Snowman
    SNOWMAN_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    SNOWMAN_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SNOWMAN_WAND_KNOCKBACK(1, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWBALL_MANA_COST(20, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWBALL_CAST_COOLDOWN(160, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWBALL_FROZEN_DURATION(30, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWBALL_VELOCITY_MULTIPLIER(2, DataValidatorBuilder.create().min(0).build()),
    SNOWMAN_SNOWSTORM_MANA_COST(40, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWSTORM_CAST_COOLDOWN(20, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWSTORM_TICK_RATE(20, DataValidatorBuilder.create().integer().min(1).build()),
    SNOWMAN_SNOWSTORM_TICKS(3, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWSTORM_RADIUS(8, DataValidatorBuilder.create().min(0).build()),
    SNOWMAN_SNOWSTORM_REQUIRE_LINE_OF_SIGHT(false, DataValidatorBuilder.create().bool().build()),
    SNOWMAN_SNOWSTORM_FROZEN_DURATION(80, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_SNOWSTORM_SLOWNESS_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SNOWMAN_SNOWSTORM_SLOWNESS_DURATION(80, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_IMBUE_MANA_COST(100, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_IMBUE_CAST_COOLDOWN(100, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_IMBUE_DURATION(900, DataValidatorBuilder.create().integer().min(0).build()),
    SNOWMAN_IMBUE_FREEZING_TICKS(40, DataValidatorBuilder.create().integer().min(0).build()),

    // Soldier
    SOLDIER_GRENADE_RADIUS(3, DataValidatorBuilder.create().min(0).build()),
    SOLDIER_GRENADE_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    SOLDIER_GRENADE_VELOCITY_MULTIPLIER(1, DataValidatorBuilder.create().min(0).build()),
    SOLDIER_GRENADE_KNOCKBACK_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    SOLDIER_GRENADE_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    SOLDIER_GRENADE_COOLDOWN(120, DataValidatorBuilder.create().integer().min(0).build()),
    SOLDIER_GRENADE_THROW_ICD(25, DataValidatorBuilder.create().integer().min(0).build()),
    SOLDIER_GRENADE_COUNT(2, DataValidatorBuilder.create().integer().min(1).max(64).build()),
    SOLDIER_GRENADE_IGNORE_I_FRAMES(true, DataValidatorBuilder.create().bool().build()),
    SOLDIER_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    SOLDIER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),

    // Sonic
    SONIC_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    SONIC_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SONIC_SPEED_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    SONIC_SPEED_COOLDOWN(180, DataValidatorBuilder.create().integer().min(0).build()),
    SONIC_SPEED_LEVEL(8, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SONIC_BOOM_DAMAGE(10, DataValidatorBuilder.create().min(0).build()),
    SONIC_BOOM_KNOCKBACK_MULTIPLIER(2.5, DataValidatorBuilder.create().min(0).build()),
    SONIC_BOOM_RECOIL_MULTIPLIER(0.75, DataValidatorBuilder.create().min(0).build()),
    SONIC_BOOM_COLLISION_CHECK_RADIUS(2, DataValidatorBuilder.create().min(0).build()),
    SONIC_BOOM_COLLISION_HITBOX_EXPANSION(0.25, DataValidatorBuilder.create().min(0).build()),
    SONIC_BOOM_RADIUS(8, DataValidatorBuilder.create().min(0).build()),
    SONIC_BOOM_STUN_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),

    // Spider
    SPIDER_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    SPIDER_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SPIDER_SWORD_POISON_DURATION(50, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_SWORD_POISON_LEVEL(1, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SPIDER_COBWEB_TRAP_SIZE(1, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_COBWEB_TRAP_DURATION(100, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_COBWEB_TRAP_COOLDOWN(200, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_COBWEB_MAX_COUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_COBWEB_THROW_MULTIPLIER(2, DataValidatorBuilder.create().min(0).build()),
    SPIDER_COBWEB_ITEM_DURATION(1200, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_COBWEB_THROW_COOLDOWN(10, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_COBWEB_PICKUP_DELAY(20, DataValidatorBuilder.create().integer().min(0).build()),
    SPIDER_WEAVING_LEVEL(1, DataValidatorBuilder.create().range(0, 255).integer().build()),
    SPIDER_WEAVING_WEBS_ON_DEATH(true, DataValidatorBuilder.create().bool().build()),

    // Spy
    SPY_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    SPY_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SPY_SNEAK_ATTACK_SWORD_DAMAGE(15, DataValidatorBuilder.create().min(0).build()),
    SPY_SNEAK_ATTACK_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    SPY_CLOAK_DURATION(300, DataValidatorBuilder.create().integer().min(0).build()),
    SPY_CLOAK_COOLDOWN(300, DataValidatorBuilder.create().integer().min(0).build()),
    SPY_SWIFT_SNEAK_LEVEL(3, DataValidatorBuilder.create().integer().range(1, 256).build()),
    SPY_CLOAK_RECLOAK_AFTER_SNEAK_ATTACK_ELIMINATION(false, DataValidatorBuilder.create().bool().build()),
    SPY_CLOAK_REFRESH_PERCENTAGE_AFTER_SNEAK_ATTACK_ELIMINATION(50, DataValidatorBuilder.create().range(0, 100).build()),

    // Vitalist
    VITALIST_SWORD_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    VITALIST_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    VITALIST_MAX_AMMO(24, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_AMMO_FINAL_BLOW_REWARD(12, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_AMMO_ASSIST_REWARD(6, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_AMMO_DISPENSE_COUNT(3, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_AMMO_REGENERATION_RATE(40, DataValidatorBuilder.create().integer().min(1).build()),
    VITALIST_CROSSBOW_AMMO_REGENERATION_AMOUNT(1, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_MAGAZINE_SIZE(6, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_SHOOT_COOLDOWN(10, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_RELOAD_DURATION_PER_1_AMMO(5, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_PROJECTILE_SPEED(16, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_PROJECTILE_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    VITALIST_CROSSBOW_PROJECTILE_MAX_DISTANCE(150, DataValidatorBuilder.create().min(0).build()),
    VITALIST_CROSSBOW_PIERCING_LEVEL(3, DataValidatorBuilder.create().integer().range(1, 256).build()),
    VITALIST_CROSSBOW_PROJECTILE_SPREAD(0.025, DataValidatorBuilder.create().min(0).build()),
    VITALIST_CROSSBOW_PROJECTILE_DAMAGE(2, DataValidatorBuilder.create().min(0).build()),
    VITALIST_CROSSBOW_HEALING_TICKS(3, DataValidatorBuilder.create().integer().min(0).build()),
    VITALIST_CROSSBOW_HEALING_TICK_RATE(10, DataValidatorBuilder.create().integer().min(1).build()),
    VITALIST_CROSSBOW_HEALING_TICK_POTENCY(1.5, DataValidatorBuilder.create().min(0).build()),
    VITALIST_CROSSBOW_LEFT_CLICK_ICD(5, DataValidatorBuilder.create().integer().min(0).build()),

    // Wizard
    WIZARD_SWORD_DAMAGE(7, DataValidatorBuilder.create().min(0).build()),
    WIZARD_SWORD_SPEED(4, DataValidatorBuilder.create().min(0).build()),
    WIZARD_WAND_KNOCKBACK(1, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_ZAP_MANA_COST(25, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_ZAP_CAST_COOLDOWN(40, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_ZAP_DAMAGE(6, DataValidatorBuilder.create().min(0).build()),
    WIZARD_ZAP_IGNORE_I_FRAMES(false, DataValidatorBuilder.create().bool().build()),
    WIZARD_ZAP_MAX_HITS(4, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_ZAP_ENTITY_HITBOX_SIZE(0.5, DataValidatorBuilder.create().min(0).build()),
    WIZARD_ZAP_BLOCK_HITBOX_SIZE(0.1, DataValidatorBuilder.create().min(0).build()),
    WIZARD_ZAP_STUN_DURATION(10, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_ZAP_MAX_RANGE(15, DataValidatorBuilder.create().min(0).build()),
    WIZARD_LIGHTNING_MANA_COST(75, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_LIGHTNING_CAST_COOLDOWN(120, DataValidatorBuilder.create().integer().min(0).build()),
    WIZARD_LIGHTNING_DAMAGE(10, DataValidatorBuilder.create().min(0).build()),
    WIZARD_LIGHTNING_IGNORE_I_FRAMES(false, DataValidatorBuilder.create().bool().build()),
    WIZARD_LIGHTNING_REQUIRE_LINE_OF_SIGHT(true, DataValidatorBuilder.create().bool().build()),
    WIZARD_LIGHTNING_SELF_DAMAGE_MULTIPLIER(0.5, DataValidatorBuilder.create().min(0).build()),
    WIZARD_LIGHTNING_MAX_RANGE(15, DataValidatorBuilder.create().min(0).build()),
    WIZARD_LIGHTNING_IMPACT_RADIUS(6, DataValidatorBuilder.create().min(0).build()),
    WIZARD_LIGHTNING_STUN_DURATION(40, DataValidatorBuilder.create().integer().min(0).build()),

    // Misc
    BEACON_BREAKER_DAMAGE_ADDITIVE(2, DataValidatorBuilder.create().integer().min(0).build());

    final boolean isBoolean;
    final double defaultValue;
    final DataValidator validator;
    
    KitData(boolean isBoolean, double defaultValue, DataValidator validator) {
        this.isBoolean = isBoolean;
        this.defaultValue = defaultValue;
        this.validator = validator;
    }

    KitData(double defaultValue, DataValidator validator) {
        this(false, defaultValue, validator);
    }

    KitData(boolean defaultValue, DataValidator validator) {
        this(true, defaultValue ? 1 : 0, validator);
    }

    public static double parse(KitData property, String value) throws DataValidationException {
        try {
            // Parse
            double kitDataValue;
            if (property.isBoolean()) {
                if (value.equalsIgnoreCase("true")) {
                    kitDataValue = 1;
                } else if (value.equalsIgnoreCase("false")) {
                    kitDataValue = 0;
                } else {
                    throw new DataValidationException("value must be true or false");
                }
            } else {
                kitDataValue = Double.parseDouble(value);
            }

            // Validate
            property.getValidator().validate(kitDataValue);
            return kitDataValue;
        } catch (NumberFormatException e) {
            throw new DataValidationException("value must be number");
        }
    }

    public boolean isBoolean() {
        return isBoolean;
    }

    public double getDefaultValue() {
        return defaultValue;
    }

    public DataValidator getValidator() {
        return validator;
    }
}
