package net.fortresswars.core.player;

public enum FWHealingSource {
    HEALING_POTION,
    AQUARIUS_WATER_BEAM,
    AQUARIUS_WATER_BOMB,
    AQUARIUS_SOOTHING_WATER,
    PRIEST_ABSOLUTION,
    MATH_HEALING,
    MEDIC_HEALING_STONE,
    MEDIC_POTION_SHARE,
    MERCY_HEALING,
    FISH_HEALING,
    ILLUSIONIST_FAKE_DEATH,
    SYSTEM,
    NECROMANCER_ESSENCE,
    VITALIST_HEALING,
    PRIEST_SOOTHING_LIGHT,
    DEMON_TRANSFUSION,
    DEMON_BLOOD_BOND,
    ICICLE_HEALING,
    SNOW_TRAIL_SUPPORT,
}
