package net.fortresswars.core.statistics;

import net.fortresswars.util.FWNumberFormat;

public enum FWStat {

    // TODO remove multi stats from here
    WIN_RATE("Win Rate", FWNumberFormat.PERCENT, FWStatAggregationType.SUM, false),
    EDR("EDR", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DAMAGE_RATIO("Damage Ratio", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),

    TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    TOTAL_WINS("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    TOTAL_LOSSES("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    TOTAL_DRAWS("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    BEACON_HITS("Beacon Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BEACON_DAMAGE("Beacon Damage", FWNumberFormat.PERCENT, FWStatAggregationType.SUM, false),

    KILLSTREAKS_STARTED("Killstreaks Started", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KILLSTREAKS_ENDED("Killstreaks Ended", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KILLSTREAKS_LONGEST("Longest Killstreak", FWNumberFormat.INT, FWStatAggregationType.MAX, false),

    BEACON_BREAKS("Beacons Breaks", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PLAYER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PLAYER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PLAYER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PLAYER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    PLAYER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PLAYER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PLAYER_HEALING_DONE("Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PLAYER_POTION_HEALING("Potion Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),

    AQUAMAN_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    AQUAMAN_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    AQUAMAN_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    AQUAMAN_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    AQUAMAN_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    AQUAMAN_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    AQUAMAN_TRIDENTS_HIT("Tridents Hit", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_TRIDENT_KILLS("Trident Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_FAR_TRIDENT_KILLS("Far Trident Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUAMAN_WATER_SPHERES("Water Spheres", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    AQUARIUS_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    AQUARIUS_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    AQUARIUS_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    AQUARIUS_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    AQUARIUS_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    AQUARIUS_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    AQUARIUS_MANA_CONSUMED("Mana Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_WATER_HEALING("Water Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    AQUARIUS_WATER_BEAMS("Water Beams", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    AQUARIUS_WATER_BOMBS("Water Bombs", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    ARCHMAGE_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    ARCHMAGE_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ARCHMAGE_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ARCHMAGE_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ARCHMAGE_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_SUICIDES( "Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ARCHMAGE_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    ARCHMAGE_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    ARCHMAGE_MANA_CONSUMED("Mana Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    BOMBER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    BOMBER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BOMBER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BOMBER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BOMBER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BOMBER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BOMBER_BOMBS_PLACED("Bombs Placed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_DETONATIONS("Detonations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_BOMBS_DETONATED("Bombs Detonated", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_BOMB_KILLS("Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_PLUS_2_BOMB_KILLS("+2 Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BOMBER_PLUS_3_BOMB_KILLS("+3 Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    BRUTE_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    BRUTE_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BRUTE_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BRUTE_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BRUTE_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BRUTE_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BRUTE_BERSERKS_ACTIVATED("Berserks Activated", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_AXE_SWIRLS_PERFORMED("Axe Swirls Performed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_AXE_SWIRL_KILLS("Axe Swirl Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BRUTE_AXE_SWIRL_DOUBLE_KILLS("Axe Swirl Double Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    BUFF_MASTER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    BUFF_MASTER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BUFF_MASTER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BUFF_MASTER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BUFF_MASTER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BUFF_MASTER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BUFF_MASTER_PLAYERS_BUFFED("Allies Buffed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_REGENERATION_BUFFED("Regeneration", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_ABSORPTION_BUFFED("Absorption", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_SPEED_BUFFED("Speed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUFF_MASTER_RESISTANCE_BUFFED("Resistance", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    BUILDER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    BUILDER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BUILDER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BUILDER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    BUILDER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BUILDER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    BUILDER_BRICK_KILLS("Brick Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_BRICKS_PLACED("Bricks Placed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    BUILDER_LADDERS_PLACED("Ladders Placed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    CRUSADER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    CRUSADER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    CRUSADER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    CRUSADER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    CRUSADER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    CRUSADER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    CRUSADER_SHIELD_BASHES("Shield Bashes", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_SHIELD_BASHES_HIT("Shield Bashes Hit", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_SHIELD_BASH_KILLS("Shield Bash Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_SHIELD_BASH_PLUS_2_KILLS("+2 Shield Bash Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSADER_SHIELD_BASH_PLUS_3_KILLS("+3 Shield Bash Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    CRUSHER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    CRUSHER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    CRUSHER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    CRUSHER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    CRUSHER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    CRUSHER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    CRUSHER_ANVILS_SUMMONED("Anvils Summoned", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_ANVIL_HITS("Anvil Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_ANVIL_HITS_DIRECT("Direct Anvil Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_ANVIL_HITS_INDIRECT("Indirect Anvil Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_ANVIL_KILLS("Anvil Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_DIRECT_ANVIL_KILLS("Direct Anvil Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_INDIRECT_ANVIL_KILLS("Indirect Anvil Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_DOUBLE_ANVIL_KILLS("+2 Anvil Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    CRUSHER_TRIPLE_ANVIL_KILLS("+3 Anvil Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    DEFAULT_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    DEFAULT_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEFAULT_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEFAULT_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEFAULT_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEFAULT_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEFAULT_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),

    DEMOLITIONIST_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEMOLITIONIST_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEMOLITIONIST_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEMOLITIONIST_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_BOMBS_CREATED("Bombs Created", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_BOMB_BLOCKS_BROKEN("Bomb Blocks Broken", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_BOMB_KILLS("Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_DOUBLE_BOMB_KILLS("+2 Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_TRIPLE_BOMB_KILLS("+3 Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMOLITIONIST_QUADRUPLE_BOMB_KILLS("+4 Bomb Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    DEMON_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    DEMON_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEMON_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEMON_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    DEMON_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEMON_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_POTIONS_USED("Blood Potions Used", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_CONSUMED("Blood Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_OBTAINED("Blood Obtained", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_TRANSMITTED("Blood Transmitted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_TRANSFUSED("Blood Transfused", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_HEALTH_TRANSFUSED("Health Transfused", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_HEALING("Blood Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    DEMON_HOMING_HEMOGLOBIN_SPELLS_CASTED("Homing Hemoglobin Spells Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_HOMING_HEMOGLOBIN_KILLS("Homing Hemoglobin Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_BONDS_FORMED("Blood Bonds Formed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    DEMON_BLOOD_BOND_BREAK_DEATHS("Blood Bond Break Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    ENGINEER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    ENGINEER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ENGINEER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ENGINEER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ENGINEER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    ENGINEER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    ENGINEER_METAL_USED("Metal Used", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_SENTRIES_BUILT("Sentries Built", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_SENTRY_KILLS("Sentry Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_DISPENSERS_BUILT("Dispensers Built", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_DISPENSER_POTIONS_GIVEN("Potions Given", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_ENTRANCES_BUILT("Entrances Built", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_EXITS_BUILT("Exits Built", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ENGINEER_PLAYERS_TELEPORTED("Allies Teleported", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    FISH_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    FISH_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    FISH_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    FISH_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    FISH_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    FISH_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    FISH_FISH_KILLS("Fish Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_PUFFERFISH_KILLS("Pufferfish Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_FISHPLOSIONS("Fishplosions", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_FISH_HEALING("Fish Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    FISH_THROWN("Fish Thrown", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    FISH_SHOT("Fish Shot", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    GLACIER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    GLACIER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GLACIER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GLACIER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GLACIER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GLACIER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GLACIER_ICE_BALLS_THROWN("Ice Balls Thrown", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_ENEMIES_FROZEN("Enemies Frozen", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GLACIER_SNOWDRIFT_GLIDES("Snowdrift Glides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    GOLEM_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    GOLEM_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GOLEM_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GOLEM_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GOLEM_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GOLEM_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GOLEM_MANA_CONSUMED("Mana Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_EARTH_WALLS_CREATED("Earth Walls", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_EARTH_SHATTER_KILLS("Earth Shatter Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_EARTH_SHATTERS_CASTED("Earth Shatters", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GOLEM_EARTH_SHATTER_PLUS_2_KILLS("+2 Earth Shatter Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    GRAPPLER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    GRAPPLER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GRAPPLER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GRAPPLER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GRAPPLER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GRAPPLER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GRAPPLER_BLOCKS_GRAPPLED("Blocks Grappled", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_ENTITIES_GRAPPLED("Entities Grappled", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_HOOKS_CASTED("Grappling Hooks Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_FALL_DAMAGE_TAKEN("Damage from Falling", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GRAPPLER_FALL_DEATHS("Deaths from Falling", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GRAPPLER_HOOK_KILLS("Grapple Hook Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    GUNNER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    GUNNER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GUNNER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GUNNER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    GUNNER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    GUNNER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GUNNER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    GUNNER_MACHINE_GUN_KILLS("Machine Gun Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    HITMAN_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    HITMAN_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    HITMAN_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    HITMAN_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    HITMAN_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    HITMAN_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    HITMAN_ENEMIES_TAGGED("Enemies Tagged", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_DAMAGE_POTION_KILLS("Harming Potion Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_DEBUFFS_APPLIED("Debuffs Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_DARKNESS_APPLIED("Darkness Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_GLOWING_APPLIED("Glowing Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_WEAKNESS_APPLIED("Weakness Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HITMAN_HARM_APPLIED("Harming Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    HULK_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    HULK_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    HULK_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    HULK_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    HULK_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    HULK_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    HULK_RAGE_KILLS("Rage Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_RELAX_KILLS("Relax Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_RAGE_MODE_ACTIVATIONS("Rage Mode Activations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    HULK_RAGE_MODE_DURATION("Rage Mode Duration", FWNumberFormat.TICK, FWStatAggregationType.SUM, false),

    ILLUSIONIST_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    ILLUSIONIST_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ILLUSIONIST_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ILLUSIONIST_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    ILLUSIONIST_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    ILLUSIONIST_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    ILLUSIONIST_FAKE_DEATHS("Fake Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_FUTURE_SIGHTS("Future Sights", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ILLUSIONIST_FUTURE_SIGHTS_KILLS("Future Sight Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    JUMPER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    JUMPER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    JUMPER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    JUMPER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    JUMPER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    JUMPER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    JUMPER_DISTANCE_TELEPORTED("Distance Teleported", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    JUMPER_TRANSLOCATORS_CREATED("Translocators Created", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_TRANSLOCATORS_USED("Translocators Used", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    JUMPER_TRANSLOCATORS_BROKEN("Translocators Broken", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    KANGAROO_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    KANGAROO_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    KANGAROO_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    KANGAROO_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    KANGAROO_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KANGAROO_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    KANGAROO_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    KANGAROO_STOMP_KILLS("Stomp Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    KNIGHT_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    KNIGHT_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    KNIGHT_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    KNIGHT_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    KNIGHT_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    KNIGHT_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    KNIGHT_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    KNIGHT_SHIELD_KILLS("Shield Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    MASTER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    MASTER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MASTER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MASTER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MASTER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MASTER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MASTER_SUPER_CREEPERS_CREATED("Super Creepers Created", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_CREEPERS_SPAWNED("Creepers Spawned", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_CREEPER_KILLS("Creeper Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_CREEPER_DOUBLE_KILLS("Creeper +2 Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_CREEPER_TRIPLE_KILLS("Creeper +3 Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_SUPER_CREEPER_KILLS("Super Creeper Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_SUPER_CREEPER_DOUBLE_KILLS("Super Creeper +2 Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MASTER_SUPER_CREEPER_TRIPLE_KILLS("Super Creeper +3 Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    MATHEMATICIAN_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MATHEMATICIAN_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MATHEMATICIAN_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MATHEMATICIAN_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PRACTICE_PROBLEM_TOTAL_HEALING("Practice Problem Total Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PRACTICE_PROBLEM_ALLY_HEALING("Practice Problem Ally Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PRACTICE_PROBLEM_ENEMY_HEALING("Practice Problem Enemy Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PRACTICE_PROBLEM_KILLS("Practice Problem Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PRACTICE_PROBLEMS_DISTRIBUTED("Practice Problems Distributed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PROBLEMS_SOLVED_CORRECTLY("Correct Answers", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MATHEMATICIAN_PROBLEMS_SOLVED_INCORRECTLY("Incorrect Answers", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    MEDIC_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    MEDIC_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MEDIC_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MEDIC_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MEDIC_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MEDIC_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MEDIC_PLAYERS_HEALED("Allies Healed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MEDIC_HEALING_DONE("Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),

    MERCY_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    MERCY_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MERCY_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MERCY_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MERCY_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MERCY_HEALING_DONE("Healing", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MERCY_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MERCY_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MERCY_DECAY_KILLS("Decay Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    MINER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    MINER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MINER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MINER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MINER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MINER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MINER_BLOCKS_BROKEN("Blocks Broken", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_BEACON_DAMAGE("Beacon Damage", FWNumberFormat.PERCENT, FWStatAggregationType.SUM, false),
    MINER_BEACON_HITS("Beacon Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_KILLS("Gobblestone Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_DOUBLE_KILLS("Gobblestone Double Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_TRIPLE_KILLS("Gobblestone Triple Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_COLLECTED("Gobblestone Collected", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_THROWN("Gobblestone Thrown", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_BURST("Gobblestone Burst", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MINER_GOBBLESTONE_GIVEN("Gobblestone Given", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    MUSKETEER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    MUSKETEER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MUSKETEER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MUSKETEER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    MUSKETEER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MUSKETEER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    MUSKETEER_RIFLE_SHOTS_FIRED("Rifle Shots Fired",FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    MUSKETEER_RIFLE_KILLS("Rifle Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    NECROMANCER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    NECROMANCER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NECROMANCER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NECROMANCER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NECROMANCER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    NECROMANCER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    NECROMANCER_ESSENCE_COLLECTED("Essence Collected", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_SKELETONS_SPAWNED("Skeletons Spawned", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NECROMANCER_SKELETON_KILLS("Skeleton Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    NINJA_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    NINJA_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NINJA_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NINJA_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NINJA_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    NINJA_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    NINJA_KATANA_PARRY_KILLS("Katana Parry Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_KATANA_PARRIES_PERFORMED("Katana Parries Performed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_KI_ACCUMULATED("Ki Accumulated", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_KI_CONSUMED("Ki Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NINJA_DODGES_PERFORMED("Dodges Performed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    NONE_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    NONE_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NONE_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NONE_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    NONE_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    NONE_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    NONE_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),

    PORCUPINE_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    PORCUPINE_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PORCUPINE_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PORCUPINE_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PORCUPINE_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PORCUPINE_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PORCUPINE_QUILL_KILLS("Quill Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_DOUBLE_QUILL_KILLS("+2 Quill Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PORCUPINE_TRIPLE_QUILL_KILLS("+3 Quill Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    POTION_MASTER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    POTION_MASTER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    POTION_MASTER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    POTION_MASTER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    POTION_MASTER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    POTION_MASTER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    POTION_MASTER_POTION_KILLS("Potion Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_DOUBLE_POTION_KILLS("+2 Potion Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_PLAYERS_DEBUFFED("Enemies Debuffed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_HARMING_DEBUFFED("Harming Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_SLOWNESS_DEBUFFED("Slowness Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_POISON_DEBUFFED("Poison Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    POTION_MASTER_WEAKNESS_DEBUFFED("Weakness Applied", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    PRIEST_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    PRIEST_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PRIEST_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PRIEST_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PRIEST_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PRIEST_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PRIEST_GRACE_RECEIVED("Grace Received", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LIGHT_BEAM_CASTS("Light Beam Casts", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LIGHT_BEAM_HITS("Light Beam Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LIGHT_BEAM_ALLY_HITS("Light Beam Ally Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LIGHT_BEAM_ENEMY_HITS("Light Beam Enemy Hits", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_ABSOLUTIONS("Absolutions", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LEVEL_1_ABSOLUTION("Level 1 Absolution", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LEVEL_2_ABSOLUTION("Level 2 Absolution", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LEVEL_3_ABSOLUTION("Level 3 Absolution", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LEVEL_4_ABSOLUTION("Level 4 Absolution", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_LEVEL_5_ABSOLUTION("Level 5 Absolution", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_PLAYERS_BURNED("Enemies Burned", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_BURN_KILLS("Burn Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PRIEST_HEALING_DONE("Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PRIEST_MANA_USED("Mana Used", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    PROMETHEUS_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    PROMETHEUS_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PROMETHEUS_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PROMETHEUS_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PROMETHEUS_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PROMETHEUS_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PROMETHEUS_FLAME_SPELLS_CASTED("Flame Spells Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_FIREBALLS_SPELLS_CASTED("Fireball Spells Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_IMBUE_SPELLS_CASTED("Imbue Spells Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_MANA_USED("Mana Used", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_ENEMIES_IGNITED("Enemies Ignited", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_FIRE_KILLS("Fire Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_FIREBALL_KILLS("Fireball Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_FIREBALL_DOUBLE_KILLS("+2 Fireball Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PROMETHEUS_FIREBALL_TRIPLE_KILLS("+3 Fireball Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    PYROTECHNIC_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    PYROTECHNIC_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PYROTECHNIC_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PYROTECHNIC_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    PYROTECHNIC_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PYROTECHNIC_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    PYROTECHNIC_ROCKET_KILLS("Rocket Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_PLUS_2_ROCKET_KILLS("+2 Rocket Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    PYROTECHNIC_PLUS_3_ROCKET_KILLS("+3 Rocket Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    RAVEN_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    RAVEN_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    RAVEN_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    RAVEN_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    RAVEN_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    RAVEN_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    RAVEN_MANA_CONSUMED("Mana Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_WIND_GUSTS_USED("Wind Gusts", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    RAVEN_TOTAL_FLIGHT_DISTANCE("Flight Distance", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    RAVEN_TOTAL_FLIGHT_DURATION("Flight Duration", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    RAVEN_FLIGHT_CANCELLED("Flight Cancelled", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SLIME_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SLIME_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SLIME_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SLIME_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SLIME_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SLIME_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SLIME_SLIME_ARMOR_PROVIDED("Slime Armor Provided", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_ALLY_DAMAGE_MITIGATED("Slime Armor Damage Mitigated", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SLIME_SLIMES_SUMMONED("Slimes Summoned", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_KILLS("Slime Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SLIME_SLIME_ABSORPTION_RECEIVED("Slime Absorption Received", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SNIPER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SNIPER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNIPER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNIPER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNIPER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNIPER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNIPER_HEADSHOTS("Headshots", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_HEADSHOT_KILLS("Headshot Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_KNEESHOTS("Kneeshots", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNIPER_KNEESHOT_KILLS("Kneeshot Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SNOW_GOLEM_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNOW_GOLEM_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNOW_GOLEM_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNOW_GOLEM_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_ICICLES_CASTED("Icicles Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_ICICLE_KILLS("Icicle Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_MINION_KILLS("Snow Golem Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_MINIONS_SPAWNED("Snow Golems Spawned", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_HEALING_DONE("Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_SNOW_LAYER_HEALING_DONE("Snow Layer Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_PLAYER_ICICLE_HEALING_DONE("Player Icicle Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOW_GOLEM_MINION_ICICLE_HEALING_DONE("Snow Golem Icicle Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),

    SNOWMAN_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SNOWMAN_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNOWMAN_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNOWMAN_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SNOWMAN_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOWMAN_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SNOWMAN_MANA_CONSUMED("Mana Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_SNOWBALLS_CASTED("Snowballs", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_SNOWSTORMS_CASTED("Snowstorms", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_IMBUE_SPELLS_CASTED("Imbue Spells Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SNOWMAN_ENEMIES_FROZEN("Enemies Frozen", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SOLDIER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SOLDIER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SOLDIER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SOLDIER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SOLDIER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SOLDIER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SOLDIER_GRENADE_KILLS("Grenade Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SOLDIER_PLUS_2_GRENADE_KILLS("+2 Grenade Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SONIC_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SONIC_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SONIC_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SONIC_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SONIC_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SONIC_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SONIC_SPEED_TOTAL_RUN_DISTANCE("Speed Distance", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SONIC_BOOMS("Sonic Booms", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_BOOM_KILLS("Sonic Boom Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_BOOM_PLUS_2_KILLS("+2 Sonic Boom Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SONIC_BOOM_PLUS_3_KILLS("+3 Sonic Boom Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SPIDER_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SPIDER_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SPIDER_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SPIDER_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SPIDER_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SPIDER_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SPIDER_TRAPS_SET("Traps Set", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_TRAPS_COLLECTED("Traps Collected", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPIDER_TRAPS_ACTIVATED("Traps Activated", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    SPY_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    SPY_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SPY_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SPY_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    SPY_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SPY_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    SPY_CLOAKED_KILLS("Cloaked Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_CLOAKS("Cloaks", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    SPY_CLOAKED_DEATHS("Cloaked Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    VITALIST_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    VITALIST_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    VITALIST_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    VITALIST_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    VITALIST_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    VITALIST_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    VITALIST_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    VITALIST_HEALING_DONE("Healing Done", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    VITALIST_CROSSBOW_KILLS("Crossbow Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),

    WIZARD_TIME_PLAYED("Time Played", FWNumberFormat.TIME, FWStatAggregationType.SUM, false),
    WIZARD_TOTAL_WINS_WEIGHTED("Wins", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    WIZARD_TOTAL_DRAWS_WEIGHTED("Draws", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    WIZARD_TOTAL_LOSSES_WEIGHTED("Losses", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, true),
    WIZARD_GAMES_PLAYED("Games Played", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_TOTAL_WINS_UNWEIGHTED("Wins", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_TOTAL_DRAWS_UNWEIGHTED("Draws", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_TOTAL_LOSSES_UNWEIGHTED("Losses", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_ELIMINATIONS("Eliminations", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_FINAL_BLOWS("Final Blows", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_ASSISTS("Assists", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_DEATHS("Deaths", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_SUICIDES("Suicides", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_DAMAGE_DEALT("Damage Dealt", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    WIZARD_DAMAGE_TAKEN("Damage Taken", FWNumberFormat.DOUBLE, FWStatAggregationType.SUM, false),
    WIZARD_MANA_CONSUMED("Mana Consumed", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_CHAIN_LIGHTNINGS_CASTED("Chain Lightning Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_CHAIN_LIGHTNING_KILLS("Chain Lightning Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_CHAIN_LIGHTNING_PLUS_2_KILLS("+2 Chain Lightning Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_CHAIN_LIGHTNING_PLUS_3_KILLS("+3 Chain Lightning Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_CHAIN_LIGHTNING_PLUS_4_KILLS("+4 Chain Lightning Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_LIGHTNING_STRIKES_CASTED("Lightning Strikes Casted", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_LIGHTNING_STRIKE_KILLS("Lightning Strike Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_LIGHTNING_STRIKE_PLUS_2_KILLS("+2 Lightning Strike Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    WIZARD_LIGHTNING_STRIKE_PLUS_3_KILLS("+3 Lightning Strike Kills", FWNumberFormat.INT, FWStatAggregationType.SUM, false),
    ;
    
    private final String friendlyName;
    private final FWNumberFormat statType;
    private final FWStatAggregationType aggregationType;
    private final boolean isHidden;

    FWStat(String friendlyName, FWNumberFormat statType, FWStatAggregationType aggregationType, boolean isHidden) {
        this.friendlyName = friendlyName;
        this.statType = statType;
        this.aggregationType = aggregationType;
        this.isHidden = isHidden;
    }

    public String getFriendlyName() {
        return friendlyName;
    }

    public FWNumberFormat getType() {
        return statType;
    }

    public FWStatAggregationType getAggregationType() {
        return aggregationType;
    }

    public boolean isHidden() {
        return isHidden;
    }

    public static String formatStat(FWStat stat, double value) {
        return stat.getType().formatValue(value);
    }

    public String getLeaderboardName() {
        return "statistic_" + name().toLowerCase();
    }
}
